// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greeter.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	greeter.proto

It has these top-level messages:
	HelloRequestS
	HelloResponseS
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequestS struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequestS) Reset()                    { *m = HelloRequestS{} }
func (m *HelloRequestS) String() string            { return proto1.CompactTextString(m) }
func (*HelloRequestS) ProtoMessage()               {}
func (*HelloRequestS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequestS) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloResponseS struct {
	Greeting string `protobuf:"bytes,2,opt,name=greeting" json:"greeting,omitempty"`
}

func (m *HelloResponseS) Reset()                    { *m = HelloResponseS{} }
func (m *HelloResponseS) String() string            { return proto1.CompactTextString(m) }
func (*HelloResponseS) ProtoMessage()               {}
func (*HelloResponseS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloResponseS) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func init() {
	proto1.RegisterType((*HelloRequestS)(nil), "proto.HelloRequestS")
	proto1.RegisterType((*HelloResponseS)(nil), "proto.HelloResponseS")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GreeterS service

type GreeterSClient interface {
	Hello(ctx context.Context, in *HelloRequestS, opts ...grpc.CallOption) (*HelloResponseS, error)
}

type greeterSClient struct {
	cc *grpc.ClientConn
}

func NewGreeterSClient(cc *grpc.ClientConn) GreeterSClient {
	return &greeterSClient{cc}
}

func (c *greeterSClient) Hello(ctx context.Context, in *HelloRequestS, opts ...grpc.CallOption) (*HelloResponseS, error) {
	out := new(HelloResponseS)
	err := grpc.Invoke(ctx, "/proto.GreeterS/Hello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GreeterS service

type GreeterSServer interface {
	Hello(context.Context, *HelloRequestS) (*HelloResponseS, error)
}

func RegisterGreeterSServer(s *grpc.Server, srv GreeterSServer) {
	s.RegisterService(&_GreeterS_serviceDesc, srv)
}

func _GreeterS_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequestS)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterSServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GreeterS/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterSServer).Hello(ctx, req.(*HelloRequestS))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreeterS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GreeterS",
	HandlerType: (*GreeterSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _GreeterS_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greeter.proto",
}

func init() { proto1.RegisterFile("greeter.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 139 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2f, 0x4a, 0x4d,
	0x2d, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xca, 0x5c,
	0xbc, 0x1e, 0xa9, 0x39, 0x39, 0xf9, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0xc1, 0x42, 0x42,
	0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x92,
	0x0e, 0x17, 0x1f, 0x54, 0x51, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0x6a, 0xb0, 0x90, 0x14, 0x17, 0x07,
	0xd8, 0xb8, 0xcc, 0xbc, 0x74, 0x09, 0x26, 0xb0, 0x4a, 0x38, 0xdf, 0xc8, 0x89, 0x8b, 0xc3, 0x1d,
	0x62, 0x55, 0xb0, 0x90, 0x19, 0x17, 0x2b, 0x58, 0xa7, 0x90, 0x08, 0xc4, 0x5a, 0x3d, 0x14, 0xcb,
	0xa4, 0x44, 0x51, 0x45, 0xa1, 0xa6, 0x2b, 0x31, 0x24, 0xb1, 0x81, 0xc5, 0x8d, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x67, 0xd7, 0x1b, 0x7e, 0xb5, 0x00, 0x00, 0x00,
}
